import Link from "next/link";
import type { PortfolioContent } from "@/lib/portfolio-content";
/* eslint-disable @next/next/no-img-element -- Owner-controlled HTTPS image sources. */
export function CustomerPortfolio({ content: c, preview = false }: { content: PortfolioContent; preview?: boolean }) {
 return <div className="customer-site">{preview && <div className="preview-banner">Private preview · Saved draft · <a href="/dashboard/editor">Back to editor ↗</a></div>}
 <header className="customer-nav"><a href="#home" className="customer-brand">{c.name}<span>®</span></a><nav aria-label="Portfolio"><a href="#work">Work</a><a href="#about">About</a><a href="#contact">Contact ↗</a></nav></header>
 <main><section id="home" className="customer-hero">{c.heroImage && <img src={c.heroImage} alt="" className="customer-hero-image" fetchPriority="high" />}<p className="platform-kicker">{c.role}</p><h1>{c.headline}</h1><div><p>{c.introduction}</p><a href="#work" className="platform-button">Explore my work ↘</a></div><span className="customer-location">{c.location}</span></section>
 <section id="work" className="customer-section"><div className="customer-section-top"><p className="platform-kicker">/01 — Selected work</p><h2>Made with<br/>intention.</h2></div>{c.projects.length ? <div className="customer-projects">{c.projects.map((project,i)=><article key={i}>{project.image ? <img src={project.image} alt={project.title} loading="lazy" className="customer-project-image" /> : <div className="project-placeholder" aria-hidden="true">{String(i+1).padStart(2,'0')}↗</div>}<div className="project-title-row"><h3>{project.title}</h3><span>{project.category}</span></div><p>{project.description}</p>{project.url && <a className="text-link" href={project.url} target="_blank" rel="noopener noreferrer">View project ↗</a>}</article>)}</div> : <p className="platform-muted">New work is on its way.</p>}</section>
 <section id="about" className="customer-section customer-about"><p className="platform-kicker">/02 — A little about me</p><div><h2>{c.name}</h2><p>{c.about}</p><span>{c.location}</span></div></section>
 {c.services.length>0 && <section className="customer-section"><div className="customer-section-top"><p className="platform-kicker">/03 — What I do</p><h2>Ways we<br/>can work.</h2></div>{c.services.map((service,i)=><details key={i} className="customer-service"><summary><span>/{String(i+1).padStart(3,'0')}</span>{service.title}<span className="service-plus" aria-hidden="true">+</span></summary><p>{service.description}</p></details>)}</section>}
 </main><footer id="contact" className="customer-footer"><p className="platform-kicker">Let&apos;s make something happen</p><h2>{c.footer}</h2>{c.email && <a className="customer-email" href={`mailto:${c.email}`}>{c.email} ↗</a>}<nav aria-label="Social links">{c.socials.map((social,i)=><a key={i} href={social.url} target="_blank" rel="noopener noreferrer">{social.label} ↗</a>)}</nav><div className="customer-bottom"><span>© {new Date().getUTCFullYear()} {c.name}</span><Link href="/">Made with Forma ↗</Link><a href="#home">Back to top ↑</a></div></footer></div>;
}
