"use client";
import Link from "next/link";
import { useActionState, useState } from "react";
import { useFormStatus } from "react-dom";
import type { PortfolioContent } from "@/lib/portfolio-content";
import { savePortfolio } from "./actions";
import { ImageUpload } from "@/components/platform/ImageUpload";
function SaveBar() { const { pending } = useFormStatus(); return <div className="editor-savebar"><button name="intent" value="save" className="platform-button secondary" disabled={pending}>{pending ? 'Saving…' : 'Save draft'}</button><button name="intent" value="publish" className="platform-button" disabled={pending}>Publish portfolio ↗</button><button name="intent" value="unpublish" className="platform-link" disabled={pending}>Unpublish</button><Link href="/dashboard/preview" target="_blank" className="platform-link">Preview saved draft ↗</Link></div>; }
export function Editor({ initial, slug, revision }: { initial: PortfolioContent; slug: string; revision: number }) {
 const [content, setContent] = useState(initial);
 const [state, action] = useActionState(savePortfolio, { revision });
 const field = (key: keyof Pick<PortfolioContent,'name'|'role'|'headline'|'introduction'|'about'|'location'|'email'|'heroImage'|'footer'>, label: string, multiline=false) => <label key={key}>{label}{multiline ? <textarea value={content[key]} onChange={e=>setContent({...content,[key]:e.target.value})} rows={key==='about'?6:3} maxLength={key==='about'?3000:500} /> : <input value={content[key]} onChange={e=>setContent({...content,[key]:e.target.value})} type={key==='email'?'email':'text'} maxLength={key==='heroImage'?2048:160} />}</label>;
 return <form action={action} className="platform-form editor-form"><input type="hidden" name="content" value={JSON.stringify(content)} /><input type="hidden" name="revision" value={state.revision} />
 <section><div className="editor-section-title"><span>/01</span><h2>Identity & story</h2></div><div className="editor-grid"><label>Public address <span className="platform-muted">/p/your-name</span><input name="slug" defaultValue={slug} required minLength={3} maxLength={60} pattern="[a-z0-9]+(-[a-z0-9]+)*" /></label>{field('name','Portfolio / studio name')}{field('role','Discipline or role')}{field('location','Location / availability')}{field('headline','Hero headline',true)}{field('introduction','Introduction',true)}{field('heroImage','Hero image URL')}<ImageUpload label="Upload hero image" onUpload={url=>setContent(current=>({...current,heroImage:url}))} />{field('email','Public contact email')}{field('about','About your practice',true)}{field('footer','Contact heading')}</div><p className="platform-muted">Upload your images or use HTTPS URLs from your image host. Leave contact email blank to hide it. Saving a draft does not publish its content.</p></section>
 <section><div className="editor-section-title"><span>/02</span><h2>Selected work</h2></div>{content.projects.map((project,i)=><fieldset key={i} className="editor-item"><legend>Project {i+1}</legend><div className="editor-grid">{(['title','category','description','image','url'] as const).map(key=><label key={key}>{({title:'Project title',category:'Discipline / category',description:'Project description',image:'Image URL',url:'Project link (optional)'})[key]}<input value={project[key]} maxLength={key==='description'?1500:2048} required={key==='title'} onChange={e=>setContent({...content,projects:content.projects.map((p,n)=>n===i?{...p,[key]:e.target.value}:p)})} /></label>)}</div><ImageUpload label={`Upload project ${i+1} image`} onUpload={url=>setContent(current=>({...current,projects:current.projects.map((p,n)=>n===i?{...p,image:url}:p)}))} /><button type="button" className="platform-link" onClick={()=>setContent({...content,projects:content.projects.filter((_,n)=>n!==i)})}>Remove project</button></fieldset>)}<button type="button" className="platform-button secondary" disabled={content.projects.length>=24} onClick={()=>setContent({...content,projects:[...content.projects,{title:'New project',category:'',description:'',image:'',url:''}]})}>+ Add project</button></section>
 <section><div className="editor-section-title"><span>/03</span><h2>Services</h2></div>{content.services.map((service,i)=><fieldset key={i} className="editor-item"><legend>Service {i+1}</legend><label>Title<input value={service.title} required maxLength={100} onChange={e=>setContent({...content,services:content.services.map((s,n)=>n===i?{...s,title:e.target.value}:s)})} /></label><label>Description<textarea value={service.description} maxLength={1000} onChange={e=>setContent({...content,services:content.services.map((s,n)=>n===i?{...s,description:e.target.value}:s)})} /></label><button type="button" className="platform-link" onClick={()=>setContent({...content,services:content.services.filter((_,n)=>n!==i)})}>Remove service</button></fieldset>)}<button type="button" className="platform-button secondary" disabled={content.services.length>=12} onClick={()=>setContent({...content,services:[...content.services,{title:'New service',description:''}]})}>+ Add service</button></section>
 <section><div className="editor-section-title"><span>/04</span><h2>Social links</h2></div>{content.socials.map((social,i)=><fieldset key={i} className="editor-item"><legend>Social link {i+1}</legend><label>Label<input required maxLength={40} value={social.label} onChange={e=>setContent({...content,socials:content.socials.map((s,n)=>n===i?{...s,label:e.target.value}:s)})} /></label><label>HTTPS URL<input required type="url" value={social.url} onChange={e=>setContent({...content,socials:content.socials.map((s,n)=>n===i?{...s,url:e.target.value}:s)})} /></label><button type="button" className="platform-link" onClick={()=>setContent({...content,socials:content.socials.filter((_,n)=>n!==i)})}>Remove link</button></fieldset>)}<button type="button" className="platform-button secondary" disabled={content.socials.length>=8} onClick={()=>setContent({...content,socials:[...content.socials,{label:'Website',url:''}]})}>+ Add social link</button></section>
 {state.error && <p role="alert" className="platform-error">{state.error}</p>}{state.message && <p role="status" className="platform-notice">{state.message}</p>}<SaveBar />
 </form>;
}
