import Link from "next/link";
import { PlatformHeader, PlatformFooter } from "@/components/platform/Chrome";
export const metadata = { title: { absolute: "Forma — A home for your best work" }, description: "A customizable editorial portfolio. Register, unlock with a one-time payment, and publish your own creative space.", alternates: { canonical: "/" } };
export default function Home() {
 return <div className="platform"><PlatformHeader /><main>
  <section className="platform-hero"><p className="platform-kicker">Independent work. Distinctive presence. / 2026</p><h1>Good work.<br/><span>Great presence.</span></h1><div className="hero-bottom"><p>A portfolio that feels like you.<br/>One considered template. An open canvas for your next chapter.</p><div className="platform-actions"><Link className="platform-button" href="/register">Make it yours ↗</Link><Link className="text-link" href="/template">Explore the template</Link></div></div><div className="hero-word" aria-hidden="true">forma®</div></section>
  <section className="platform-section preview-section"><div className="section-top"><p className="platform-kicker">/01 — The template</p><h2>Less noise.<br/>More you.</h2><p>Oversized type. Space to breathe. Your projects at the center.</p></div><Link href="/template" className="template-preview" aria-label="Explore the Forma portfolio template"><span className="preview-nav">YOUR STUDIO <span>WORK &nbsp; ABOUT &nbsp; CONTACT ↗</span></span><span className="preview-title">Ideas into<br/>impact.</span><span className="preview-caption">A home for your best work. <span>Explore template ↗</span></span></Link></section>
  <section className="platform-section"><div className="section-top"><p className="platform-kicker">/02 — How it works</p><h2>From account<br/>to out there.</h2></div><div className="steps">{[['01','Make it official.','Register your account. Your workspace stays private until you publish.'],['02','Unlock your space.','A single payment unlocks the editor. Review your exact price in secure checkout.'],['03','Make it yours.','Edit your identity, story, services and projects. Preview, then publish at your own Forma address.']].map(([n,title,body])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
  <section className="platform-section platform-offer"><p className="platform-kicker">/03 — One template. Your possibilities.</p><h2>A place to<br/>call your own.</h2><div><p>One-time purchase. Your own editor. A shareable portfolio URL. No recurring template subscription.</p><ul><li>Personal branding and contact details</li><li>Project and service collections</li><li>Private drafts and public publishing</li><li>Responsive layouts, from phone to desktop</li></ul><Link className="platform-button" href="/register">Create your account ↗</Link></div></section>
 </main><PlatformFooter /></div>;
}
